spring:
  datasource:
    url: jdbc:h2:mem:expensetracker;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: warn
app:
  jwt:
    secret: ${APP_JWT_SECRET:dev_secret_change}
    expiration-ms: 86400000

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/expensetracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
